#! python
""" Convert object names to coordinates by SIMBAD
    
Context : SRP
Module  : SRPNameResolver
Author  : Stefano Covino
Date    : 02/08/2014
E-mail  : stefano.covino@brera.inaf.it
URL:    : http://www.merate.mi.astro.it/utenti/covino
Purpose : Convert objects names to coordinates

Usage   : SRPNameResolver [-v] [--version]

    
History : (02/08/2014) First version.
"""

__version__ = '1.0.0'


import argparse
from SRP.SRPCatalogue.SimbadNameClass import SimbadName


parser = argparse.ArgumentParser()
parser.add_argument("-n", "--name", action="store", help="Object name", metavar='n', required=True)
parser.add_argument("-v", "--verbose", action="store_true", help="Fully describe operations")
parser.add_argument("--version", action="version", version=__version__)
options = parser.parse_args()


#
d = SimbadName (options.name)
try:
    rs = d.GetCoords()
    if options.verbose:
        print("Coordinates for object %s are RA,DEC = %s" % (options.name, str(rs)))
    else:
        print("%s %.5f %.5f" % (options.name, rs.RA, rs.DEC))
except:
    if options.verbose:
        print("No coordinates found for object: %s" % options.name)
    else:
        print("")
#
