#! python
""" Code to create SRP Session name

Context : SRP
Module  : SRPSessionName.py
Version : 1.0.3
Author  : Stefano Covino
Date    : 02/05/2011
E-mail  : stefano.covino@brera.inaf.it
URL:    : http://www.merate.mi.astro.it/utenti/covino
Purpose : Manage the creation of a SRP Session File Name

Usage   : SRPSessionName [-h] -n arg [-v]
            -n allows one to provide a base prefix for many of the files
            created by other SRP commands.

Remarks : 

History : (20/05/2003) First version.
        : (22/05/2003) Better help.
        : (03/02/2005) Optparse.
        : (02/05/2011) Better documentation.
"""



from optparse import OptionParser
import SRP.SRPConstants as SRPConstants
import SRP.SRPFiles as SRPFiles


parser = OptionParser(usage="usage: %prog [-v] [-h] -n arg", version="%prog 1.0.3")
parser.add_option("-n", "--name", action="store", nargs=1, type="string", dest="basefilename", help="Base name for any created file")
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", help="Fully describe operations")
(options, args) = parser.parse_args()


if options.basefilename:
    f=SRPFiles.SRPFile(SRPConstants.SRPLocalDir,SRPConstants.SRPSessionName,SRPFiles.WriteMode)
    f.SRPOpenFile()
    f.SRPWriteFile(options.basefilename)
    f.SRPCloseFile()
    if options.verbose:
        print("Base file name will be: %s." % options.basefilename)
else:
    parser.print_help()
