#! python
""" Code to show SRP running version.

Context : SRP
Module  : SRPVersion.py
Version : 1.0.0
Author  : Stefano Covino
Date    : 17/08/2011
E-mail  : stefano.covino@brera.inaf.it
URL:    : http://www.merate.mi.astro.it/utenti/covino
Purpose : Show SRP version.

Usage   : SRPVersion [-h] [-v]
 

History : (17/08/2011) First version.
"""

from optparse import OptionParser
import SRP

parser = OptionParser(usage="usage: %prog [-h] [-v]", version="%prog 1.0.0")
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", help="fully describe operations")
(options, args) = parser.parse_args()


if options.verbose:
    print("SRP running version is: %s" % SRP.__version__)
else:
    print("%s" % SRP.__version__)
    
